# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Deploy Static HTML to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy HTML to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'SSW-webapp'  # Erstat med dit Azure Web App-navn
          package: .  # Dette angiver den aktuelle mappe som kilde til deployment
